[workspace]
members = [
    "promptgen-cli",
    "promptgen-core",
    "promptgen-ui",
]
resolver = "3"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds
[profile.dev.package."*"]
opt-level = 2
